version: '2.1'
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@2.0.0
jobs:
  test:
    # working_directory: app
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
          working_directory: app
workflows:
  test_my_app:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
            account-url: AWS_ACCOUNT_URL
            region: AWS_REGION
            repo: 'space-stone-front'
            tag: '${CIRCLE_SHA1}'
            requires:
              - test
      - aws-ecs/deploy-service-update:
          cluster-name: 'meruplanet-cluster'
          container-image-name-updates: 'container=meruplanet-api-container,tag=${CIRCLE_SHA1}'
          family: 'meruplanet-front-task'
          service-name: "meruplanet-front-service"
          requires:
            - aws-ecr/build-and-push-image
            # - aws-ecr/build-and-push-image