# version: '2.1'
# orbs:
#   node: circleci/node@5.0.2
# jobs:
#   build:
#     # working_directory: ~/space_stone_front/app
#     docker:
#       - image: cimg/node:16.15.0
#     steps:
#       - checkout
#         # path: ~/space_stone_front/app
#       - node/install-packages:
#           pkg-manager: yarn
#   test:
#     # working_directory: ~/space_stone_front/app
#     parallelism: 1
#     docker:
#       - image: cimg/node:16.15.0
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - run:
#           command: yarn test
#           name: テストの実行
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build

# version: '2.1'
# orbs:
#   node: circleci/node@5.0.2
# jobs:
#   install-node-example:
#     docker:
#       - image: 'cimg/base:stable'
#     steps:
#       - checkout
#       - node/install:
#           install-yarn: true
#           node-version: '16.13'
#       - run: node --version
# workflows:
#   test_my_app:
#     jobs:
#       - install-node-example

version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    # working_directory: /space_stone_front/appoko
    # executor:
    #   name: node/default
    #   tag: '16'
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
          working_directory: app
workflows:
  test_my_app:
    jobs:
      - test