version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  test:
    parallelism: 1
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: テストの実行
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build