version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    # working_directory: app
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
          working_directory: app
workflows:
  test_my_app:
    jobs:
      - test