version: '2.1'
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@2.0.0
jobs:
  test:
    # working_directory: app
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
          working_directory: app

  build_and_set:
    machine:
      # image: ubuntu-1604:201903-01
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          command: 
            echo -e \\nNEXT_PUBLIC_P_GOOGLE_KEY=${GOOGLE_KEY} >> app/.env.production
          name: env_google
      - run:
          command: 
            echo -e \\nNEXT_PUBLIC_AUTH_URL=${AUTH_URL} >> app/.env.production
          name: env_google
      - run:
          command: 
            echo -e \\nNEXT_PUBLIC_TWITTER_URL=${TWITTER_URL} >> app/.env.production
          name: env_google
      #  - run:
      #     command: 
            # echo NEXT_PUBLIC_A5=7>>app/.env.production
            # echo NEXT_PUBLIC_P_GOOGLE_KEY=${GOOGLE_KEY} >> app/.env.production
            # {
            #   echo "aaa"
            #   echo "bbb"
            #   echo "ccc"
            # } >> data.txt
            # echo NEXT_PUBLIC_P_GOOGLE_KEY=GOOGLE_KEY >> app/.env.production
          # name: env2
      - run:
          command: echo "$(<app/.env.production)"
          name: env3
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: 'space_stone_front'
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          checkout: false
      # - run:
      #     command: echo "$(<app/.env.production)"
      #     name: env6
      # - checkout
      # - run:
      #     command: echo ${GOOGLE_KEY}
      #     name: env3

workflows:
  test_my_app:
    jobs:
      - test
      - build_and_set:
          requires:
            - test


      # - aws-ecr/build-and-push-image:
      #       account-url: AWS_ACCOUNT_URL
      #       region: AWS_REGION
      #       repo: 'space_stone_front'
      #       tag: '${CIRCLE_SHA1}'
      #       extra-build-args: "echo NEXT_PUBLIC_A5=a55555555555>>app/.env.production"
      #       extra-build-args: "--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}"
      #       path: ./app
      #         command: echo NEXT_PUBLIC_A5=a55555555555>>app/.env.production
      #       requires:
      #         - test
      #         - test2
      - aws-ecs/deploy-service-update:
          cluster-name: 'meruplanet-cluster'
          container-image-name-updates: 'container=meruplanet-front-container,tag=${CIRCLE_SHA1}'
          family: 'meruplanet-front-task'
          service-name: "meruplanet-front-service"
          requires:
            - build_and_set
            # - aws-ecr/build-and-push-image